### ISSUE TITLE
cntools unable to find pool keys that are present

### ISSUE THREAD

**Issue by rssfed23** [cardano-community/guild-operators#1121]
**Describe the bug**
When going in to modify or retire our pool, we get this message:

![Screenshot 2021-09-29 at 16 29 26](https://user-images.githubusercontent.com/12484127/135300613-8ea9038d-8db0-4846-921f-5fd1c08dbf4d.png)

However, the pool files are there in /opt/cardano/cnode/priv/pool/FLICK

![Screenshot 2021-09-29 at 16 30 16](https://user-images.githubusercontent.com/12484127/135300750-0d9fb262-20d9-4838-ba26-d4f3f3bf703e.png)

We've not changed any of the default path locations in the env file (only the POOL_NAME variable), and have run the unprotect script. As you'll see in the screenshot I've also tried lazing the file permissions (since undone) but to no avail.

One thing that I wonder if it's impacting this, is when doing pool > list the pool is showing as not registered, however it is registered on chain (shown when doing pool > show).

I'm wondering what kind of diagnostics or troubleshooting I can try here in order to be able to make modifications to the pool, or if there's something glaringly obvious that I've missed. The pool was originally created and registered using cntools (hybrid mode), although cntools does seem to give me the option to register the pool again. It does seem as if while the pool is registered, something in my setup makes cntools think it's not despite the keys being there and valid. It does give me the option to rotate KES keys successfully however.

**Version:**
 - OS: Ubuntu 20.10
 - Product version: CNTools v8.6.5
 - Cardano Node version: 1.29.0
 - Network you're connecting to: mainnet

**Comment by Scitz0** [comment]
The error message could be better here, it expects a pool.cert file to be available indicating that the pool is registered. There is no good way to verify if the pool is registered or not so this is the current way for this detection. Created when first registering the pool. 

You can easily fool CNTools by adding a dummy file with:
`touch /opt/cardano/cnode/priv/pool/FLICK/pool.cert`

The idea is to later use Koios for this purpose. See Catalyst fund6 proposal.

The current solution to query ledger through cli is not a viable solution due to node/memory load it adds.

Closing issue.

**Comment by rssfed23** [comment]
Thank you so much - I'm not sure why I didn't have pool.cert, but touching it sorted everything out :)!
