### ISSUE TITLE
Even with the latest env file, the message "Script update(s) detected, *****" is displayed when starting gliveview.

### ISSUE THREAD

**Issue by btbf** [cardano-community/guild-operators#1239]
**Describe the bug**
If you change the environment setting values in the env file, you will always see "Script update(s) detected, do you want to download the latest version? (yes/no):" at startup.
If you select "yes" here, close and then re-launch giliveview, the same message will be displayed.

**Expected behavior**
Don't show an error if the code is the same as git master, even if the environment variable path has been changed

**Additional context**

`if [[ ($3 = Y && "$(sha256sum "${PARENT}/${1}" | cut -d' ' -f1)" != "$(sha256sum "${PARENT}/${1}.tmp" | cut -d' ' -f1)") || "$(echo ${OLD_STATIC} | sha256sum)" != "$(echo ${NEW_STATIC} | sha256sum)" || "$(echo ${OLD_TEMPL} | sha256sum)" != "$(echo ${GIT_TEMPL} | sha256sum)" ]]; then
      update_msg="\nScript update(s) detected, do you want to download the latest version?"`

This code compares the current env with the env retrieved from git, but I think ...

1) "$(sha256sum "${PARENT}/${1}" | cut -d' ' -f1)" != "$(sha256sum "${PARENT}/${1}.tmp" | cut -d' ' -f1)"
    Will never match if the environment variable is changed. 

2)  $(echo ${OLD_TEMPL} | sha256sum)" != "$(echo ${GIT_TEMPL} | sha256sum)"
    
`    # replace default CNODE with custom name if needed
    [[ ${CNODE_VNAME} != cnode ]] && sed -e "s@/opt/cardano/[c]node@/opt/cardano/${CNODE_VNAME}@g" -e "s@[C]NODE_HOME@${CNODE_VNAME_UPPERCASE}_HOME@g" -i "${PARENT}/${1}".tmp`
    
This code will change all the variable names in env.tmp, and the hash values will not match!

Why is this process included?

**Comment by rdlrt** [comment]
1. The part of condition you're comparing is if [ $3 is set to Y ](https://github.com/cardano-community/guild-operators/blob/10db40d4e3a3093e14faf38a9213e5196b1ba28f/scripts/cnode-helper-scripts/env#L137), that's set to N for updates.

2. The code follows documentations on guild-operators repository. If you're manually changing top level folders (eg: changing CNODE_HOME to /opt/cardano/tnode in env , instead of using prereqs.sh -t tnode), without using guidance from prereqs, you end up in cases that we would not have catered for. This is a legitimate use case used by many.


> Why is this process included?

To combine updates to a single prompt instead of asking for a confirmation for each file.

When coming from older version, you may have missed announcement in announcements channel about why the change was made, how it was done and the fact that coming from older version which did not have such code might likely prompt you two times for standard setup and three times if using custom paths

**Comment by btbf** [comment]
Well noted, and thank you.
