### ISSUE TITLE
cabal-build-all.sh error

### ISSUE THREAD

**Issue by lbcrypt** [cardano-community/guild-operators#1573]
When trying to build 1.35.4 on Ubuntu 22.04.1 (Totally clean install) you get an error saying it can not build cardano-ping.

-node/build/cardano-node/cardano-node-tmp/Main.o )
Linking /home/lbaker/git/cardano-node/dist-newstyle/build/x86_64-linux/ghc-8.10.7/cardano-node-1.35.4/x/cardano-node/build/cardano-node/cardano-node ...
cabal: Cannot build the package cardano-ping, it is not in this project
(either directly or indirectly). If you want to add it to the project then
edit the cabal.project file.

Copying cardano-submit-api to /home/lbaker/.cabal/bin/
Copying cardano-cli to /home/lbaker/.cabal/bin/
Copying cardano-node to /home/lbaker/.cabal/bin/

**Comment by lbcrypt** [comment]
I followed this procedure with the exception of I installed alpha branch

https://www.lbcrypt.com/cnode-on-ubuntu-22-02-minimal-server/

**Comment by rdlrt** [comment]
1.35.4 isn't supported yet on guild-ops repo (we'd anyways be removing cardano-ping support, as it's already provided by cncli - moving away from IO utilities that aren't considered mainstream by their CI).

As regards reason for the error, IO moved their build dependencies to [CHaP](https://github.com/input-output-hk/cardano-haskell-packages), and - for 1.35.4 - didn't have `network-mux`. It has since been reverted in master of `cardano-node` repo, and CHaP also has the dependencies met. With 1.35.5 around the corner , wouldn't make sense to change the script atm for this intermediate release, the existing functionality of components are not impacted.

**Comment by rdlrt** [comment]
cabal install related commands are now disabled by default, and would only come into play when using `-c` . Meanwhile, documents are updated to include note (and option to pre-download binaries). Hence, closing
