### ISSUE TITLE
bech32 not being detected

### ISSUE THREAD

**Issue by cloudstake** [cardano-community/guild-operators#1590]
CNTools 10.0.5
Ubuntu 20.04

bech32 Linux binary is in on the system, entered in path statement and has been verified by "bech32 --version" producing the version output (1.1.2). I've ruled out the basics like letter case, permissions, etc. 

Running Wallet | Import | Mnemonic gives message:
"ERROR: bech32 and/or cardano-address not found in 'PATH' Please run updated prereqs.sh and re-build cardano-node .... press any key to proceed "

2023-01-02 00:38:51 PST [INFO]    >> WALLET >> IMPORT >> MNEMONIC
2023-01-02 00:38:51 PST [DEBUG]  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-01-02 00:38:51 PST [ERROR]  ERROR: bech32 and/or cardano-address not found in '$PATH'
2023-01-02 00:38:51 PST [ERROR]  Please run updated prereqs.sh and re-build cardano-node

Problem is both online and offline

Re-downloaded prereqs.sh and built cardano-node and did not resolve the problem.

**Comment by rdlrt** [comment]
The error message talks about bech32 and/or cardano-address, based on description - it is likely that you might be missing cardano-address in your $PATH. Running prereqs does not download the build binaries , that'd be part of cabal-build-all script output, except for node-1.35.4 (they've fixed it since, but using that tag will result in cardano-address not being built by cabal build scripts), IO's cabal project files fail for `install` command. You can download pre-built `cardano-address` binary from their [github releases page](https://github.com/input-output-hk/cardano-addresses/releases/latest)
