### ISSUE TITLE
upgrade?  seems like if my version is higher than available version - it should not show message

### ISSUE THREAD

**Issue by papacarp** [cardano-community/guild-operators#319]
CNTools version check...

A new version of CNTools is available

Installed Version : 2.0.0
Available Version : 1.2.

Go to Update section for upgrade

**Comment by Scitz0** [comment]
Its because the genesis branch version of cntools you run checks against master branch that is not updated yet. 
I guess script could be improved to only warn if there is a version higher and not only if current doesn't match with git.
In most cases though if it doesn't match it means there is a newer version available.

Because of this, I think we can close this issue. Will most likely not be an issue going forward.
