### ISSUE TITLE
CNTOOLS cnode.sh doesn't match documentation

### ISSUE THREAD

**Issue by Gary6502** [cardano-community/guild-operators#363]
Documentation on this page: https://cardano-community.github.io/guild-operators/Setup-Node.html

Shows the $POOLNAME variable being used but not in cnode.sh
 --CNTools doesn't appear to copy the keys to the PRIV folder but expects to find them there.

Also shelley-kes-key line uses kes.skey instead of hot.skey

**Comment by rdlrt** [comment]
Setup Node page is to give the syntax for starting node. When you run prereqs.sh, you will get a passive node template.
Once you register a pool, the screen prompts you for bits to add.
We cannot add a static value in the document for starting as pool operator because this path will be different for each user

**Comment by rdlrt** [comment]
The page is now removed in #372, and we use cnode.sh instead to avoid confusion
