### ISSUE TITLE
Use forked version of libsodium

### ISSUE THREAD

**Issue by rene84** [cardano-community/guild-operators#421]
**Describe the bug**
The [instructions](https://github.com/cardano-community/guild-operators/blob/master/docs/Build/node-cli.md) and [script](https://github.com/cardano-community/guild-operators/blob/2ffb4951440a8686fa2739bcc3694c17b93200a9/scripts/cnode-helper-scripts/prereqs.sh#L135) to build the cardano-node and cardano-cli use the flag -external-libsodium-vrf. This flag is a convenience flag to set up a development environment and should not be used in production deployment as is described here:

https://github.com/input-output-hk/cardano-node/issues/1355#issuecomment-650733459
and for more information here
https://github.com/input-output-hk/cardano-base/commit/e91f5a406ee940532b39b7de54f2b0dd75fe6af6

The recommended way to build is to build and install the forked version of libsodium as per:

https://docs.cardano.org/projects/cardano-node/en/latest/getting-started/install.html

**Comment by rdlrt** [comment]
Yes - this is known and intentional.
While IOG prefers to use their fork, its ~ **2 years old**, and its a matter of time when a version change (eg: glibc) introduces a complexity that works with updated system but borks the existing fork.
IOG themselves are looking to upstream their changes so that the system provided libraries and the fork are same, which may take months.

But the C bindings are kept up to date as well, the fork isnt being updated , which means there arent breaking changes being added. This makes it easier and more beneficial long term to depend on the stable version accepted universally , than risk a production system using an outdated fork version

**Comment by mark-stopka** [comment]
> IOG themselves are looking to upstream their changes so that the system provided libraries and the fork are same, which may take months.

Upstream won't accept the modification until there is a stable spec, I've spoke with upstream months ago.

**Comment by rene84** [comment]
Thanks. Wasn't aware it was intentional. All good
