### ISSUE TITLE
CNTools - cardano-node 1.19.0 compatibility

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#430]
There are a couple of changes made in 1.19.0 that most likely will be a breaking change for CNTools 5.3.4 and below. 

* pool id now saved as bech32 by default, --output-format hex command available to get both formats
* small change to stake-address-info, unclear if it's a breaking one or not.

Add to list if you notice other breaking changes.

**Comment by rdlrt** [comment]
stake-address-info looks alright

**Comment by Scitz0** [comment]
stake-address-info contain bech32 encoding of pool id. Not sure how to best handle this, I see these options:
1) Ignore the issue and only use hex
    - Pool name won't show in, wallet»list/show or wallet selection menus
2) Save an additional pool id file called for example pool.id-bech32
3) Reformat pool.id to a JSON that contain both hex and bech32 enc of pool id.

For both 2 & 3, a new library helper function to return these ids are to be added.
The issue with 2 & 3 is backward compatibility as we need cold.vkey on disk to be able to derive both id formats. 
For new pools, it's not a problem as we can get both formats.
For now, 1 is the easiest solution but we lose some of the functionality.

**Comment by Straightpool** [comment]
I think we should go with option 3. This way we are the most flexible on further pool id changes. SPOs should know how to secure their keys e.g. using temporary encrypted ramdisks etc.

**Comment by rdlrt** [comment]
Problem with reformat is (and my biggest concern with any changes to existing files):
- Users at large did not really understand what happened behind the scenes.
- Files backed up and deleted from cntools might get restored and show errors due to version incompatibility.

As compared to that, I prefer option 2 the most - so that the change is not breaking:
if bech32 file is used, we display it
else we use pool.id for hex display (anyways used for querying ledger-state)

That is assuming we dont add any overhead of conversion tools/binaries between hex and bech32.

**Comment by Scitz0** [comment]
Fix for stake-address-info added to commit c0598b2 using solution 2 from above.
