### ISSUE TITLE
CNTools - Pre-built cross-platform thin vm for offline tx signing

### ISSUE THREAD

**Issue by Scitz0** [cardano-community/guild-operators#517]
Adding as a reminder for future enhancement opportunities. 

A pre-built turn-key low resource VM with CNTools that is cross-platform would make it easier to handle private keys offline.

Suggestions and more details for how this could be added are welcomed.

**Comment by TrevorBenson** [comment]
OVA and/or OVF's are a good solution to a generic VM definitions which can be imported in most virtualization systems (although some require more effort than others). It require some testing to ensure it works however. For instance entries for devices (cdrom, floppy, scsi controllers) in some virtualization systems use different ID's (integers) and an export of an OVA/OVF from one system may not import cleanly on another, making OVA/OVF is not as ubiquitous as intended

This should be possible, but does require testing imports to ensure they work on virt systems different from what the OVA/OVF was exported from. 

1. Removing all unnecessary devices (CDROM, Floppy, NIC, etc) from the VM will reduce troubleshooting on some systems and entirely eliminate it for others.
2. LSI SCSI device should be acceptable and available in almost all virtualization platforms, although there still may be ID conflicts with some systems. Do not use vmare paravirtual scsi drivers if exporting from Fusion/ESXi/vSphere, as many other virt systems do not converted pvSCSI into LSI or another available controller, causing errors on import.

Food for thought: 

- A container with `--network none` flag prevents the container from having a network.
- Both VM's and Containers are images which can be mounted back to the host OS. LUKS disk based encryption could protect the image from being mounted if the host OS is compromised.

**Comment by Scitz0** [comment]
Thanks for the input... will take it into consideration when its time to take a closer look at this.

**Comment by TrevorBenson** [comment]
@Scitz0 I was considering building a sample OVA for this feature request and performing testing, as I've done this quite a few times in the past and have resources to test against OSX, Linux and commercial options. I could test for multiple versions/products for VMware, including vSphere/ESXi, Workstation & Fusion, as well as VirtualBox & libvirt.

1. 1. Was your goal to have a terminal only based interface or would you prefer a full GUI environment.
2. I'm assuming Ubuntu would be the most likely target for the VM, but would be willing to build another OS if that was the preference.

If you'd prefer to handle this yourself that is fine. I wanted to offer assistance as I've been in charge of enterprise virtualization environments and building tempaltes as well as OVA's in past positions.

**Comment by redoracle** [comment]
> @Scitz0 I was considering building a sample OVA for this feature request and performing testing, as I've done this quite a few times in the past. I also have resources to test against OSX & Linux for free and commercial options. I can test for multiple versions/products for VMware, including vSphere/ESXi, Workstation & Fusion, as well as VirtualBox & libvirt.
> 
> 1. Was your goal to have a terminal only based interface or would you prefer a full GUI environment.
> 2. I'm assuming Ubuntu would be the most likely target for the VM, but would be willing to build another OS if that was the preference.
> 
> If you'd prefer to handle this yourself that is fine. I wanted to offer assistance as in past positions I've been in charge of designing enterprise virtualization architectures, including building templates as well as OVA's.

Is it simpler using a docker container?

**Comment by Scitz0** [comment]
We welcome any contribution to the project so if you feel this is an area were you can help out go for it. 

1) As this was meant to be created exclusively for offline signing in CNTools there is really no need for a gui. But i really don't have any preference here. Some might feel its easier to use with a gui if you are to mount an usb etc. A lightweight gui in this case.

2) Ubuntu is a fine os, not sure it's the most lightweight though. It's good if we can keep the image as small as possible.  My first thought was to use Alpine. They also provide an optimized ready to go vm you can download from their website to build upon.

The idea was that it would either launch CNTools automatically on boot or at least provide instructions for how to start it. If users need to mount usb keys this needs to be done before launching CNTools. 

cardano-cli, cntools.sh, cntools.library, cntools.config and env should be the only files needed. But will most likely need some of the prerequisites installed by prereqs.sh as well.

**Comment by Scitz0** [comment]
> Is it simpler using a docker container?
Containers are great, small and lightweight. I'm no expert on them but from my understanding, you can not run a Linux container on Windows as it shares the underlying kernel?

**Comment by TrevorBenson** [comment]
> Is it simpler using a docker container?

Yes, building one which works in multiple container systems is easier/less time than testing an OVA for successful importing. In that regards an image is like an ISO, it works or it doesn't as the OS & container platform are of less concern.

> Containers are great, small and lightweight. I'm no expert on them but from my understanding, you can not run a Linux container on Windows as it shares the underlying kernel?

Windows has Docker Desktop and osx has Kitematic (name changed, forget the new name ATM) and both of those load a light weight VM with 1-2GB of RAM. I believe under virtual box, or used to be, and then leverage that Linux VM to spawn containers.

My description may be dated, I haven't used either of those in a year or more now, so some things may have changed. But I'd bet they both still leverage a Linux VM for kernel sharing unless they found a better solution somehow.

**Comment by Scitz0** [comment]
I leave the implementation up to you you as long as it checks all the boxes for easy cross-platform deployment and lightweight.
Utilize the KISS principle as much as possible, it only has to be able to run CNTools in offline mode.

**Comment by TrevorBenson** [comment]
I have containers already built for my own uses that leverage cntools (5.4 and 6.x)  which could be used for basic testing immediately. Leaving only the documentation on how to pull the image, run the container and map the pool keys into the container. So testing could commence almost immediately once I have documentation and then I could obtain feedback from you and other contributors.

Did you envision the operators bare-metal would:

1. Maintain a fully offline stature, only using USB as a "sneaker net" to update the container for new CNtools versions.
2. Maintain a network connection and pull a new container directly from network then disconnecting only during transaction signing? 

I can create documentation for either but wanted to ask what your preference is since you came up with the original idea. Each method would have different documentation to ensure security of keys and keep steps as simple as possible.

**Comment by Scitz0** [comment]
The idea was to keep it entirely offline and that you load wallet and pool keys from USB into VM/container. 
When a new release of CNTools is released that affect the offline parts of CNTools, a new VM/Container image has to be created and made available. So the offline VM is not meant to be kept up-to-date by network connection and pulling the latest version. 

But given that the usage offline will be limited to signing transactions and rotating KES keys, these parts of CNTools are rarely modified so doesn't have to be in sync with "live" CNTools unless these functions are affected.

**Comment by TrevorBenson** [comment]
Adding some notes here which will go into a branch later. A few nuances need to be fixed in the images I am using to be viable for offline use cases. I was using podman and utilizing rootless containers, meaning root user was mapped to my local cardano user, but inside the container it believed it was the root user. This prevents container privilege escalation of root. Given that most users will likely be using docker and not podman I will rebuild the current images so they are using cardano user and prevent privilege escalation for those working with docker versions that would allow root escalation. After that, the following documentation is worth testing.

Procedure currently obtains a container which has cardano-node and cntools. Once rebuilt to use the cardano user for non podman rootless environments it will contain cardano-node 1.21.1 (unless a newer release has hit mainnet) and cntools 6.1.1, gLiveView 1.9, etc..

ONLINE NODE STEPS: 
1. `docker pull docker.io/chaincrucial/cardano-node:latest` 
2. `docker save docker.io/chaincrucial/cardano-node:latest | gzip > cardano-node_cntools.tar.gz`
3. Connect the USB drive and copy to the tarball to it, disconnect drive and sneakernet to OFFLINE NODE

OFFLINE NODE STEPS:
1. `docker load cardano-node_cntools.tar.gz`
2. `docker run -dit --name offline_wallet docker.io/chaincrucial/cardano-node:latest /bin/bash`
3. `docker exec -it --user cardano offline_wallet /bin/bash`

This runs the container in a detached mode using bash as an entry point, so cardano-node will not be started. The docker attach command would be another way to just attach to the current bash process, however if the user types "exit" it stops the entrypoint and they will have to start the container manually before attaching next. So to keep the offline wallet container running using docker exec to attach is simpler as the user can exit and rerun the exec to re-attach. An alternative is to exec cntool.sh directly instead of /bin/bash. However decrypt/encrypt functionality inside the container is not working ATM. I have not dig into why selecting decrypt/encrypt causes the screen to flash, yet does not open the menu system to select a wallet. This is another fix that should be put in place to simplify the offline_wallet process.

**Comment by TrevorBenson** [comment]
@Scitz0 So I figured out what the problem is with encryption/decryption inside the container. 

1. `chattr` is not installed in containers by default, so choosing decrypt/encrypt not pass the `protectionPreRequisites()` function.
2. installing `chattr` does not resolve the issue, as permissions to change attributes are blocked inside the container, even if SELinux is not enabled.
3. I tried both rootful and rootless containers with and without SELinux even the root user in the container does not have permissions for `chattr`.

I was able to remove the test inside `protectionPreRequisits()` for chattr being present and the results of if it works. As long as keys are not already locked/immutable then this restores the decrypt/encrypt functionality.

I can also work around this another way besides removing chattr requirements from cntools.libary by:

- running a full rootful container (a container started by the bare metal hosts root user)
- escalating the container privileges with `--privileged` flag

While a rootful container is probably the most common way an offline_wallet user would run (since it's rare to find people using podman) the `--priviledged` flag is not something I am happy with suggesting, even though it is for an offline wallet. 

I also realized I had SELinux disabled from earlier chattr tests, so it is possible it actually requires SELinux disabled in addition to rootful and privileged. If disabling SELinux is also required would make me very unhappy with the solution, but I need to retest to know. I'd prefer a solution that allows disabling chattr requirements vs. the multiple security requirements it places on an offline_wallet container.

**Comment by Scitz0** [comment]
Great work... I will test it out when I get some time, need to complete the current work with CNCLI + metadata transaction first.

It sounds like disabling chattr is the best option. 

Three actions/changes will be made.
1) Provide an option in cntools.config to disable it
2) Check for its existence in code before trying to use it.
3) In backup function on the live node if chattr is used, first disable this lock, make backup and enable again.

**Comment by TrevorBenson** [comment]
Sounds good. Once we have a CNTools release that provides your changes I will retest.

**Comment by TrevorBenson** [comment]
> 2\. My first thought was to use Alpine.

Forgot to mention before, I spent awhile on this converting package names from Ubuntu & CentOS package names to package names in Alpine, also finding which version of Alpine covered the most requirements. 

In the end while it was trivial to install nix or cabal and compile cardano-node from source providing every requirement for CNTools was where I decided to stick with something that `./prereqs.sh` supports. I decided not to open a feature request for it thinking it was probably a very low volume of users needing it while potentially increasing the amount of effort for CNTools to maintain and/or update `./prereqs.sh` when OS's update or go EOL.
