### ISSUE TITLE
Pool info shows wrong registered info

### ISSUE THREAD

**Issue by marco-martins** [cardano-community/guild-operators#549]
**Describe the bug**
After update to the version 6.0.1 going to the section “Pool” > “Show” its shows “Registered: NO”.
But in the "Pool" > "List" it shows "Registered: YES". Anyway, the pool it's working as expected.

**To Reproduce**
1. Pool [p]
2. Show [s]

**Screenshots**

<img width="400" alt="Captura de ecrã 2020-10-16, às 12 57 13" src="https://user-images.githubusercontent.com/147888/96252167-d14c5200-0fb1-11eb-8d89-1bdb1968482b.png">

<img width="400" alt="Captura de ecrã 2020-10-16, às 12 56 54" src="https://user-images.githubusercontent.com/147888/96252188-da3d2380-0fb1-11eb-83a0-ce3f51d01fdb.png">

**Version:**
 - OS: [e.g. Ubuntu 20.04.1 LTS]
 - Product version: [e.g. CNTools 6.0.1]
 - Cardano Node version: 1.21.1 // a8193114
 - Network you're connecting to: mainnet

**Additional context**
I noticed also that the retrieve of the pool information takes longer than usual.

**Comment by Scitz0** [comment]
Fixed in #550

Pool id syntax in cardano-cli 1.21.2 is changed. This was included in CNTools a bit prematurely. 6.0.2 soon to be released include a fix for this as well as a fix for the internal update that is broken in 6.0.[0-1].
Use prereqs.sh to update, **without** -f flag. It will then retain all user config settings and the update should be smooth.
