### ISSUE TITLE
Enhancement to password protected keys

### ISSUE THREAD

**Issue by signallhill** [cardano-community/guild-operators#564]
Not sure if this is already being worked on or maybe it is not possible but I think this will make working with cntool more effective.

If keys are locked and user wants to change pool or do anything that requires encrypted keys. Ask for the password during the process and then relock the keys once used

For example 
User has encrypted keys
User selects Modify Pool
CNTOOL checks if the keys are encrypted
CNTOOL asks for password - decrypts the keys
User modifies the pool successfully
CNTOOL encrypts the keys with the password provided earlier
CNTOOL exits the process and if the transaction is not success it encrypts the keys and exits with the same password.

This way the key is always encrypted.

**Comment by TrevorBenson** [comment]
I've thought about this myself and checked the code previously. CNTools actually does an `unset password` to undefine the variable the moment the password is finished being used. With Meltdown, Spectre and this years CSME security flaws I would prefer that the password stay in memory for as short of a time as possible. Even though `unset` provides no guarantee that the memory was returned to the OS and/or overwritten, reducing the exposure/footprint for exploitation is a good practice and I think CNTools should maintain this posture.

If this feature request is approved instead of keeping the password stored until the re-encryption step I suggest that the password be requested twice. Once to decrypt the keys and then again later to encrypt them.

While it requires an extra step and entering a password twice it provides options like:
1. Skipping encryption altogether so more transactions could be performed with the decrytped keys before finally encrypting them again.
2. Rotating the password during encryption.
3. Restoring the original password.

**Comment by Scitz0** [comment]
This was actually the initial implementation. It adds more complexity to the code than you might initially think though, mainly to handle all cases when stuff fail, aborted etc. In the end I got tired of fixing all edge cases that came up, it was just easier to let the user handle it manually.

**Comment by signallhill** [comment]
Yes if this brings more complexity, I think the current way is probably better. I will close this.
