### ISSUE TITLE
topologyupdater with testnet not working

### ISSUE THREAD

**Issue by ststolz** [cardano-community/guild-operators#604]
**Describe the bug**
topologyupdater is not working with testnet. 

**To Reproduce**
My node tried to fetch with this URL:
https://api.clio.one/htopology/v1/fetch/?max=15&magic=1097911063

and got:

> { "resultcode": "402", "datetime":"2020-11-26 10:43:22", "clientIp": "81.169.186.68", "iptype": 4, "msg": "IP is not allowed to fetch this list",  "Producers": [ { "addr": "relays-new.cardano-mainnet.iohk.io", "port": 3001, "valency": 2 } ]  }

**Expected behavior**
I think the problem hast to do with the fact that "relays-new.cardano-mainnet.iohk.io" is used and not "relays-new.cardano-testnet.iohk.io". Because magic was set, i expected that I get a testnet request.

**Comment by gufmar** [comment]
after checking the subscribe and fetch logfiles I see the IP 81.169.186.68 started subscribing with 

```
26.11.2020 10:22:35 - 81.169.186.68     - QRST: port=7031&blockNo=5000084&valency=1&magic=1097911063&hostname=81.169.186.68
26.11.2020 10:22:36 - 81.169.186.68     - INFO: 201 nice to meet you
```
this was the first request.
according to https://cardano-community.github.io/guild-operators/#/Scripts/topologyupdater?id=start-the-script you need to schedule and execute this subscribe request once a hour, by always showing your node is on tip with it's `blockNo`. (quality control)
I can't see no other requests from this IP since then. So it was never added to the allowed list of IPs who can fetch a topology. 

I've sone one additional request 24 minutes after the first, but executed from a different source IP. (masked part of it because I believe it might is your private internet connection, where you did a debug request, by using the original URL from your node)

```
26.11.2020 10:46:04 - 149.1xx.1xx.9     - QRST: port=7031&blockNo=5000084&valency=1&magic=1097911063&hostname=81.169.186.68
26.11.2020 10:46:05 - 149.1xx.1xx.9     - ERROR: 501 hostname 81.169.186.68 not pointing to ip 149.1xx.1xx.9
```

I recommend to schedule the subscribe request and wait for 2 hours. then your node should be allowed to fetch remote peers. 

Something unclear to me is, why your request returned the default topology, despite you specified the testnet magic. Verified just now and received the testnet default topology.

**Comment by ststolz** [comment]
I overlooked this fact. Thank you for your detailed help! Will try. 

testnet is working now. I think the reason could be, that I first used the version from master branch, which is linked at [cardanoupdates.com](https://cardanoupdates.com/docs/c5f6eda6-cd55-4db5-8bbe-dceb56c6701d). Now I use alpha version.
