### ISSUE TITLE
cntools.sh errors out with "press any key" on startup

### ISSUE THREAD

**Issue by alexanderwatanabe** [cardano-community/guild-operators#631]
**Describe the bug**
cntools.sh displays "press any key" when started up.

**To Reproduce**
1. Fresh install (minimal? not sure provided by VPS provider) of ubuntu 20.04
2. Follow guild docs (run ./prereqs.sh -c -l, source .bashrc, build node & wallet)
3. Run ./cntools.sh after editing env and other scripts

I was able to trace the behavour back to cntools.library by grepping ' "press any key" ' in the scripts directory, from there i looked for library in cntools.sh and found line 75 where it checks for command line utils being available. Checked them manually 1 by 1 and found everything was there EXCEPT column. Installed it with sudo apt install bsdmainutils and now I can run cntools again.

I guess this a hidden dependency that prereqs.sh is not picking up?

**Version:**
 - OS: [Ubuntu 20.04]
 - Product version: [e.g. CNTools 6.2.1]
 - Cardano Node version: [1.23.0]

**Comment by Scitz0** [comment]
Fixes for this has been deployed in development branch(alpha). Not recommended to run on mainnet due to the fact that its development code and require future node version for allegra era (next hard fork on 16/12).

List of required applications for cntools to work:
- curl
- jq
- bc
- sed
- awk
- column
- gpg
- systemd-ask-password (removed in alpha)
- chattr (can be disabled)

You can check that the commands exist by running e.g. `command -v gpg`. If you get the path to the executable its installed.
chattr support can be disabled in cntools.config

**Comment by Scitz0** [comment]
Fixed in alpha branch that will be merged to master and become official just before allegra HF.
