### ISSUE TITLE
disable auto-update of gLiveView by default

### ISSUE THREAD

**Issue by sacrelege** [cardano-community/guild-operators#704]
gLiveView is used by a lot of cardano node operators, which certainly reflects how useful and nice this script is!

But the auto update poses a security risk.

May I suggest to just notify the user if there is a newer version available and let them run the upgrade procedure with '--update' or ask them in an interactive way "upgrade now (Y/n)". This would give the users at least the option to review the new version first before they run it on their nodes.

A configuration option to always force an auto update can of course be implemented (for the brave who like the old behavior back).

**Comment by rdlrt** [comment]
The version updates are already prompted for. The env file, however, is shared across multiple tools, and due to users not being up to date with latest announcements for tools not necessarily used, it makes it difficult to support the queries.

The input that will be taken onboard will be giving the accessibility to set a User variable to turn offline mode on. We expect the users to RTFM, and those who need to will be allowed to have that option on config to use an offline mode.

**Comment by sacrelege** [comment]
I think I need to apologize, I use gLiveScript only without the whole rest of the CNTools.. so it only applies to my specific situation. Gonna close this - thanks for your time.

**Comment by rdlrt** [comment]
Will be sorted via #708
