### ISSUE TITLE
Run as Service User

### ISSUE THREAD

**Issue by ResponsibleStaking** [cardano-community/guild-operators#826]
**Describe the bug**
The Installation procedure currently installs Cnode and all Services in context of the currently logged in user.
This user needs to have SUDO priviledges which is not optimal for a service.
Services should run as linux system services to prevent priviledge escalation attack vectors.

**To Reproduce**
Following the Basics Guides: https://cardano-community.github.io/guild-operators/#/basics
Then build and start the Node: https://cardano-community.github.io/guild-operators/#/Build/node-cli

**Expected behavior**
The install should create a service user or ask for one. (adduser cnode-service --system)
This service user should be used for starting the services which are created in deploy-as-systemd.sh

**Version:**
 - OS: Debian 4.19
 - Product version: CNTools 7.1.6
 - Cardano Node version: 1.25.1

Unfortunately I'm only able to create a bug. Propably you would want to change it to Enhancement.

**Comment by rdlrt** [comment]
Thanks for the report. If you wouldnt mind, I would convert this issue to a discussion thread.

> This user needs to have SUDO priviledges which is not optimal for a service.

For running prereqs (updating OS packages, setting permissions to subfolders where parent is owned by root, ...), yes - but that is not a permanent requirement. The only point the user needs root post the prereqs is if they're using chattr from cntools.

We do highlight the sysops requirements (which are individual since every admin has his own preferences and rules) in the guide:
![image](https://user-images.githubusercontent.com/3169068/110256717-7d88e680-7fee-11eb-8d4b-12d2af3e6a45.png)

The scripts and systemd services can be customised as desired assuming you retain the permissions as well, but you'd rather not have sudo access post deployment for your requirement.
