### ISSUE TITLE
cannot expose Prometheus port

### ISSUE THREAD

**Issue by lesinigo** [cardano-community/guild-operators#908]
**Describe the bug**

I want to gather metrics through Prometheus from my host running `cardano-node` in a Docker container.

By default it is listening only on `127.0.0.1` inside the container so I cannot get to it even with a Docker `--publish`, it would need to be listening on all IP addresses (inside the container) but I'm failing to let it listen on `0.0.0.0`.

**To Reproduce**

I tried both setting `PROM_HOST` from Docker and customizing it in the `env` file:

1. start the container
```
   docker run -d \
    --name cardano \
    --security-opt=no-new-privileges \
    -e NETWORK=mainnet \
    -e PROM_HOST=0.0.0.0 \
    -p 6000:6000 \
    -p 127.0.0.1:12798:12798 \
    -v /srv/cardano/cnode/env:/opt/cardano/cnode/scripts/env \
    -v /srv/cardano/cnode/priv:/opt/cardano/cnode/priv \
    -v /srv/cardano/cnode/db:/opt/cardano/cnode/db \
    cardanocommunity/cardano-node
```

2. `config.json` still has 127.0.0.1 for Prometheus, it is ignoring my `PROM_HOST` env, so I try editing `env` and set `PROM_HOST=0.0.0.0`
3. `docker restart cardano`

**Expected behavior**
The `/opt/cardano/cnode/files/config.json` inside the container should have:
```json
  "hasPrometheus": [
    "0.0.0.0",
    12798
  ],
```

... but it always ends up with:
```json
  "hasPrometheus": [
    "127.0.0.1",
    12798
  ],
```

**Version:**

I'm using `cardanocommunity/cardano-node:latest` with image id `68be4f44ffa5`, its banner at startup is:
```
cardano-node 1.26.2 - linux-x86_64 - ghc-8.10
git rev 3531289c9f79eab7ac5d3272ce6e6821504fec4c
```

For what it's worth, I tried changing `PROM_PORT` in the same way (either by editing `env` or by setting an environment variables from Docker) without any success.

On the other hand, if I add `-e CNODE_PORT=6001` to my Docker command line, it will correctly change the port of `Cardano-node`, without any need to edit the `env` file.

Finally, copying `config.json` on my host and mounting it inside the container does not seem a viable option because the container `entrypoint.sh` always runs `prereqs.sh` with the `-f` option that triggers a complete rewrite of the file.

**Comment by rdlrt** [comment]
Hi @lesinigo 
I will just reply while @TrevorBenson @redoracle might be busy..

PROM_HOST/PROM_PORT specifies the host that the guild tools (CNTools/gLiveView) will connect "to" , not where your node instance will listen "on".
I am not sure why you'd want to open prom to listen to all addresses instead of binding/exposing ports, but to listen ON that port, you'd need to add a sed command from Dockerfile for your config.json.

Whether this should be a seperate argument or reuse of variable, is a valid feedback that I'll leave @redoracle to decide on, but meanwhile you can simply add a sed command (or use bind/expose to map the port) instead.

**Comment by lesinigo** [comment]
> PROM_HOST/PROM_PORT specifies the host that the guild tools (CNTools/gLiveView) will connect "to" , not where your node instance will listen "on".

I found that out later on and afaik the file I need to config for where the node will listen "on" is `config.json` - then I need to make sum e`PROM_HOST`/`PROM_PORT` are set accordingly to let guild tools work correctly. That's why at the end of my original issue I specified that I tried to find a way to let `config.json` have what I want and I digged in the `entrypoint.sh` and `prereq.sh` scripts. AFAIK mounting `config.json` from the host is not the way to go since the container wants to download and override it at every start (commanded by `prereq.sh`).

> I am not sure why you'd want to open prom to listen to all addresses instead of binding/exposing ports, but to listen ON that port, you'd need to add a sed command from Dockerfile for your config.json.

I would be super perfectly happy with binding/exposing and that's what I usually do. Maybe I'm missing something here, but how should I go at exposing something that inside the container is listening only on `127.0.0.1` ? AFAIK `EXPOSE` and/or `--publish` work by setting up the `docker-proxy` userland service to forward traffic to a port on _the first *non loopback* network interface inside the container_ (eg. `eth0@something` and not `lo`). There are some more details for this kind of situation in [this StackOverflow Q/A](https://stackoverflow.com/a/52518929).

If I'm understanding this correctly, the Prometheus endpoint of `cardano-node` in the container will be accessible only by processes _running inside the container itself_ and is completely unreachable (and useless) for anything _outside_ of the container unless instructed to listen on `0.0.0.0`, which also shouldn't be a security concern because the operator must explicitly `--publish` the port to make it reachable from the network.

**Comment by redoracle** [comment]
Hi lesinigo, sorry for my very late reply.
about: "If I'm understanding this correctly, the Prometheus endpoint of cardano-node in the container will be accessible only by processes running inside the container itself and is completely unreachable (and useless) for anything outside of the container unless instructed to listen on 0.0.0.0, which also shouldn't be a security concern because the operator must explicitly --publish the port to make it reachable from the network." 

- I can confirm that unless published or unless you are using the host network instead of your private network than anything will be published. Nevertheless is always a good practise to use nmap to scan your IPs and check from the outside what ports can be reached. :)

While about the PROM_HOST parameter, I will make sure I include that in the docker logic too, sorry I missed it :), will be implemented asap.

**Comment by redoracle** [comment]
The issue has been resolved.
