### ISSUE TITLE
use symbolic links for pool and wallet files

### ISSUE THREAD

**Issue by rakewell** [cardano-community/guild-operators#923]
hi community,

This may be possible already (not a Linux expert here). I want to create symbolic links to folders under the /priv/wallet and /priv/pool folders to link to my external USB device (accessed via vbox shared folders at the moment) to access private keys. I would rather not copy these keys to the local machine and have them accessed only from the external USB device (which is protected by security code). When i create the symbolic links these are viewable in the command line and Nautilus but when running CNTOOLS (ether as the current user or SUDO) the wallets and pools don't show up (Pool > List, Wallet > List).

**Comment by rdlrt** [comment]
The code currently used to check directories is below (in cntools.library file, look for getDirs function):

while IFS= read -r -d '' dir; do
    dirs+=("$(basename ${dir})")
  done < <(find "${1}" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

Instead of symlinks, I believe you'd want to use `mount` command instead, unless you want to customise the function for your use case

**Comment by rakewell** [comment]
@rd

> 
> 
> The code currently used to check directories is below (in cntools.library file, look for getDirs function):
> 
> while IFS= read -r -d '' dir; do
> dirs+=("$(basename ${dir})")
> done < <(find "${1}" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)
> 
> Instead of symlinks, I believe you'd want to use `mount` command instead, unless you want to customise the function for your use case

Works like a charm, thank you so much.
